apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: menu-item-annotation-setting
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: text
      name: icon
      label: 图标
      placeholder: iconfont icon-home
      help: 支持 Iconfont 类名
