apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-clarity
spec:
  displayName: Clarity
  author:
    name: Handsome&纸鹿
    website: https://www.xhhao.com
  description: 一款注重阅读体验的三栏博客主题，用清晰的设计让阅读回归本真
  logo: /themes/theme-clarity/assets/images/logo.svg
  homepage: https://www.xhhao.com
  repo: https://github.com/acanyo/theme-clarity
  issues: https://github.com/acanyo/theme-clarity/issues
  settingName: "theme-clarity-setting"
  configMapName: "theme-clarity-configMap"
  version: "1.0.4-alpha.1"
  requires: ">=2.22.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/acanyo/theme-clarity/blob/main/LICENSE"
